language: go

os:
    - osx
    - linux
    - windows

go:
  - 1.13.x
  - 1.14.x

before_install:
  - cd ${TRAVIS_BUILD_DIR}
  - go get -u golang.org/x/lint/golint

before_script:
  - gofmt -l ./...
  - go vet -v ./...
  - $HOME/gopath/bin/golint ./...
