language: go

os:
    - osx
    - linux
    - windows

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

jobs:
  allow_failures:
    # Master is not available on windows?
    - os: windows
      go: master

before_install:
  - cd ${TRAVIS_BUILD_DIR}
  - go get -u golang.org/x/lint/golint

before_script:
  - gofmt -l .
  - go vet ./...
  - $HOME/gopath/bin/golint ./...
  - $HOME/gopath/bin/ineffassign ./*
  - $HOME/gopath/bin/gocyclo -over 15 .

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
