config:
    accounts:
        # where are our accounts stored?
        path: "~/.bitmaelum/account"

    # How can we resolve public keys and accounts
    resolve:
        local:
            path: "~/.bitmaelum/.resolvecache"
        remote:
            url: "https://resolver.bitmaelum.com"
