config:
    accounts:
        # where are our accounts stored?
        path: "~/.mailv2/account"

    # How can we resolve public keys and accounts
    resolve:
        local:
            path: "~/.mailv2/.resolvecache"
        remote:
            url: "https://resolve.mailv2.nl"
