config:
    logging:
        # LogLevel
        level: trace
    account:
        # Allows users to create an account
        registration: true
        # How many bits of proof-of-work must be completed to register a new account
        proof_of_work: 22
        # Path to our email accounts
        path: .maildb
    server:
        # Address where to listen. Use 0.0.0.0 for all interfaces
        host: 127.0.0.1
        # Default port to listen on
        port: 2424
    tls:
        # Certification and key files
        certfile: server.crt
        keyfile: server.key
    redis:
        # Redis host
        host: 127.0.0.1:6379
        db: 0
