
#
# BitMaelum Server Configuration Template
#
config:
    # Logging of information
    logging:
        # LogLevel: trace, debug, info, warn, error, crit
        log_level: trace
        
        # Where to store logs. Can be one of the following:
        #   file:<path>,  
        #   stdout 
        #   syslog
        log_path: syslog

        # Log apache-style HTTP combined log 
        apache_log: true
        # Path to apache logfile
        apache_log_path: "/bitmaelum.apache.log"
    accounts:
        # Allow users to create an account on this server (with no limitations currently)
        registration: false
        
        # How many bits of proof-of-work must an account have to be able to register here
        proof_of_work: 22
   
    paths:
        processing: /bitmaelum/processing
        retry: /bitmaelum/retry
        incoming: /bitmaelum/incoming
        accounts: /bitmaelum/messagedb
    server:
        hostname: foobar.bladieblah.foo.us.gov

        # Address where to listen. Use 0.0.0.0 for all interfaces
        host: 0.0.0.0

        # Default port to listen on
        port: 2424
    tls:
        # Certification and key for running on HTTPS. This should be a valid certificate via LetEncrypt 
        # for instance.
        # You can use self-signed certificates is you want
        certfile: /bitmaelum/certs/server.cert
        keyfile: /bitmaelum/certs/server.key
    redis:
        # Redis host where we store information
        host: redis:6379
        # Redis Database Number (defaults to 0)
        db: 0
    resolver:
        # Local resolver cache 
        local:
            path: "/bitmaelum/.resolvecache"
        # Remove resolver
        remote:
            url: "https://resolver.bitmaelum.com"
