---
swagger: "2.0"
info:
  description: "This is BitMaelum API server"
  version: "0.0.1"
  title: "BitMaelum swagger"
host: "bitmaelum.swagger.io"
basePath: "/"
schemes:
- "https"
paths:
  /account:
    post:
      tags:
      - "account"
      summary: "Create a new account"
      description: "This request will create a new account on the server if registration is available."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Account info"
        required: true
        schema:
          $ref: "#/definitions/AccountCreate"
        x-exportParamName: "Body"
      responses:
        "400":
          description: "Invalid input, invalid proof of work or not enough number of bits"
        "403":
          description: "Registration not allowed"
  /account/{mailbox}/key:
    get:
      tags:
        - "account"
      summary: "Retrieve the public key for this mailbox"
      description: "Retrives the public key for this mailbox."
      responses:
        "200":
          description: "Public key in PEM format"
        "404":
          description: "Mailbox not found"


definitions:
  AccountCreate:
    type: "object"
    properties:
      mailbox:
        type: "string"
        description: "The SHA256 of the address"
      public_key:
        type: "string"
        description: "PEM formatted public RSA key"
      proof_of_work:
        type: "object"
        properties:
          bits:
            type: "integer"
            format: "int64"
            description: "Number of bits for this proof"
          proof:
            type: "integer"
            format: "int64"
            description: "Actual proof based on the mailbox"
